FROM python:3-slim
WORKDIR /app

COPY requirements-simulator.txt .
RUN pip install --no-cache-dir -r requirements-simulator.txt

COPY simulator/desaladora_sim.py .

EXPOSE 502

CMD ["python3", "desaladora_sim.py"]